# frontend/netlify.toml
[build.environment]
  REACT_APP_BACKEND_URL = "https://backend-production-6b38.up.railway.app" 
  
  # frontend/netlify.toml
[build]
  command = "npm run build"
  publish = "build"
  
  [[redirects]]
  from = "/api/*"
  to = "https://backend-production-6b38.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200